import Head from "next/head";
import NavBar from './NavBar';
import Container from "react-bootstrap/Container";

const Layout = ({children}) => {
  return (
    <Container>
      <Head>
        <title>My app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <NavBar/>
      </header>
      <main>{children}</main>
    </Container>
  );
};

export default Layout;
